<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Learn without limits | Atlas</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-[#fcfbf8] font-sans text-ink">
    <header class="border-b border-slate-200/70 bg-[#fcfbf8]/90 backdrop-blur-md">
        <div class="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10">
            <a href="{{ url('/') }}" class="flex items-center gap-3">
                <span class="flex h-9 w-9 items-center justify-center rounded-xl bg-ink text-base font-extrabold text-white">A</span>
                <span class="font-display text-lg font-bold tracking-tight">atlas<span class="text-coral">.</span></span>
            </a>
            <nav class="hidden items-center gap-8 text-xs font-bold text-slate-500 md:flex">
                <a href="#catalog" class="transition hover:text-ink">Explore</a>
                <a href="#method" class="transition hover:text-ink">Our approach</a>
                <a href="#footer" class="transition hover:text-ink">About Atlas</a>
            </nav>
            <div class="flex items-center gap-2 sm:gap-3"><a href="{{ url('/api/documentation') }}" target="_blank" rel="noreferrer" class="hidden items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-extrabold text-slate-600 transition hover:border-slate-300 hover:text-ink sm:inline-flex">Swagger API Docs <svg class="h-3.5 w-3.5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M7 17L17 7m0 0H8m9 0v9"/></svg></a><a href="{{ route('admin.login') }}" class="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-2.5 text-xs font-extrabold text-white shadow-lg shadow-ink/10 transition hover:bg-slate-800 sm:px-5">Admin portal <svg class="h-3.5 w-3.5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5 12h13m-5-5l5 5-5 5"/></svg></a></div>
        </div>
    </header>

    <main>
        <section class="relative overflow-hidden">
            <div class="absolute -right-40 top-10 h-[480px] w-[480px] rounded-full bg-orange-100/60 blur-3xl"></div>
            <div class="absolute -left-48 top-72 h-[380px] w-[380px] rounded-full bg-blue-50/70 blur-3xl"></div>
            <div class="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[0.9fr_1.1fr] lg:px-10 lg:pb-28">
                <div>
                    <div class="mb-7 inline-flex items-center gap-2 rounded-full border border-orange-200 bg-orange-50 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[0.16em] text-coral"><span class="h-1.5 w-1.5 rounded-full bg-coral"></span> Learn at your pace</div>
                    <h1 class="max-w-xl font-display text-5xl font-bold leading-[1.04] tracking-[-0.055em] text-ink sm:text-6xl lg:text-[70px]">Skills for the<br><span class="text-coral">next chapter.</span></h1>
                    <p class="mt-7 max-w-md text-base leading-7 text-slate-500">Practical courses, expert-led lessons, and a learning path built around the way you work.</p>
                    <div class="mt-9 flex flex-wrap items-center gap-3"><a href="#catalog" class="rounded-xl bg-coral px-5 py-3 text-xs font-extrabold text-white shadow-lg shadow-coral/20 transition hover:bg-[#f15e3d]">Start exploring <span class="ml-2">→</span></a><a href="#method" class="rounded-xl border border-slate-200 bg-white px-5 py-3 text-xs font-extrabold text-ink transition hover:border-slate-300">How it works</a></div>
                    <div class="mt-12 flex items-center gap-4"><div class="flex -space-x-2"><span class="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#fcfbf8] bg-[#f4c7a1] text-[10px] font-bold text-ink">JM</span><span class="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#fcfbf8] bg-[#b8d7ca] text-[10px] font-bold text-ink">AL</span><span class="flex h-8 w-8 items-center justify-center rounded-full border-2 border-[#fcfbf8] bg-[#d8c3e8] text-[10px] font-bold text-ink">RK</span></div><p class="text-xs font-semibold text-slate-400"><strong class="text-ink">12,000+</strong> curious people learning with us</p></div>
                </div>
                <div class="relative mx-auto w-full max-w-[570px]">
                    <div class="absolute -left-3 top-16 z-10 rounded-2xl border border-white bg-white p-3.5 shadow-xl shadow-slate-300/30 sm:-left-8"><div class="flex items-center gap-2"><span class="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-50 text-emerald-500"><svg class="h-4 w-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg></span><div><p class="text-[10px] font-extrabold text-ink">Learning streak</p><p class="mt-0.5 text-[10px] font-semibold text-slate-400">7 days in a row</p></div></div></div>
                    <div class="rounded-[30px] bg-[#17243a] p-3 shadow-2xl shadow-slate-300/50 sm:p-4"><div class="overflow-hidden rounded-[21px] bg-[#f6f7f9]"><div class="flex items-center justify-between border-b border-slate-200/80 bg-white px-5 py-4"><div class="flex items-center gap-2"><span class="flex h-7 w-7 items-center justify-center rounded-lg bg-coral text-[10px] font-extrabold text-white">A</span><span class="text-xs font-extrabold text-ink">My learning space</span></div><span class="h-6 w-6 rounded-full bg-orange-100"></span></div><div class="grid gap-5 p-5 sm:grid-cols-[1.1fr_0.9fr] sm:p-7"><div><p class="text-[10px] font-extrabold uppercase tracking-[0.17em] text-coral">Good morning, Alex</p><h2 class="mt-2 font-display text-2xl font-bold tracking-[-0.04em] text-ink">Keep your<br>momentum going.</h2><div class="mt-6 rounded-2xl bg-ink p-4 text-white"><div class="flex items-center justify-between"><span class="text-[10px] font-bold text-slate-400">Current course</span><span class="text-[10px] font-extrabold text-coral">62%</span></div><p class="mt-3 text-sm font-bold">Designing better systems</p><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div class="h-full w-[62%] rounded-full bg-coral"></div></div><p class="mt-3 text-[10px] font-semibold text-slate-400">8 of 13 lessons complete</p></div></div><div class="rounded-2xl border border-slate-200 bg-white p-4"><div class="flex items-center justify-between"><p class="text-[10px] font-extrabold text-ink">This week</p><span class="text-[10px] font-bold text-emerald-500">+24%</span></div><div class="mt-5 flex h-28 items-end justify-between gap-2"><span class="h-[35%] w-full rounded-t bg-orange-100"></span><span class="h-[52%] w-full rounded-t bg-orange-200"></span><span class="h-[43%] w-full rounded-t bg-orange-100"></span><span class="h-[75%] w-full rounded-t bg-coral"></span><span class="h-[63%] w-full rounded-t bg-orange-200"></span><span class="h-[88%] w-full rounded-t bg-coral"></span><span class="h-[96%] w-full rounded-t bg-ink"></span></div><div class="mt-3 flex justify-between text-[9px] font-bold text-slate-400"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div></div></div><div class="flex items-center justify-between border-t border-slate-200 bg-white px-5 py-3.5"><p class="text-[10px] font-semibold text-slate-400">3 recommendations for you</p><span class="text-xs font-extrabold text-coral">Browse all →</span></div></div></div>
                    <div class="absolute -bottom-5 -right-2 hidden rounded-2xl border border-white bg-white px-4 py-3 shadow-xl shadow-slate-300/30 sm:block"><p class="text-[10px] font-extrabold text-ink">Course completion</p><p class="mt-1 font-display text-xl font-bold text-ink">86%</p></div>
                </div>
            </div>
        </section>

        <section id="catalog" class="border-y border-slate-200/70 bg-white py-16 sm:py-20">
            <div class="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-[10px] font-extrabold uppercase tracking-[0.2em] text-coral">Curated for growth</p><h2 class="mt-3 font-display text-3xl font-bold tracking-[-0.04em] text-ink">Find your next focus.</h2></div><a href="{{ route('login') }}" class="text-xs font-extrabold text-coral hover:underline">Sign in to see your catalog →</a></div><div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article class="rounded-2xl bg-[#fff6ee] p-5"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-coral"><svg class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M4 18.5A2.5 2.5 0 016.5 16H20M6.5 4H20v16H6.5A2.5 2.5 0 014 17.5v-11A2.5 2.5 0 016.5 4z"/></svg></span><h3 class="mt-8 text-sm font-extrabold">Product & design</h3><p class="mt-2 text-xs leading-5 text-slate-500">Think clearly. Make things people need.</p><p class="mt-5 text-[10px] font-extrabold uppercase tracking-wider text-coral">24 courses</p></article><article class="rounded-2xl bg-[#eef6ff] p-5"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-blue-500"><svg class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4"/></svg></span><h3 class="mt-8 text-sm font-extrabold">Technology</h3><p class="mt-2 text-xs leading-5 text-slate-500">Build with confidence and ship better.</p><p class="mt-5 text-[10px] font-extrabold uppercase tracking-wider text-blue-500">18 courses</p></article><article class="rounded-2xl bg-[#f5f0ff] p-5"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-violet-500"><svg class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21a9 9 0 100-18 9 9 0 000 18zm0-13v4l2.5 2.5"/></svg></span><h3 class="mt-8 text-sm font-extrabold">Leadership</h3><p class="mt-2 text-xs leading-5 text-slate-500">Lead teams that do meaningful work.</p><p class="mt-5 text-[10px] font-extrabold uppercase tracking-wider text-violet-500">12 courses</p></article><article class="rounded-2xl bg-[#effaf5] p-5"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-emerald-500"><svg class="h-5 w-5" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M4 19V5m0 14h16M8 16v-3m4 3V8m4 8v-6"/></svg></span><h3 class="mt-8 text-sm font-extrabold">Business</h3><p class="mt-2 text-xs leading-5 text-slate-500">Turn good ideas into lasting impact.</p><p class="mt-5 text-[10px] font-extrabold uppercase tracking-wider text-emerald-500">16 courses</p></article></div></div>
        </section>

        <section id="method" class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div class="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p class="text-[10px] font-extrabold uppercase tracking-[0.2em] text-coral">A better way to learn</p><h2 class="mt-3 max-w-md font-display text-3xl font-bold leading-tight tracking-[-0.04em] text-ink sm:text-4xl">Small steps.<br>Real progress.</h2><p class="mt-5 max-w-sm text-sm leading-6 text-slate-500">Atlas gives you the structure to start, the space to practice, and the momentum to keep going.</p></div><div class="grid gap-5 sm:grid-cols-3"><div class="border-t-2 border-coral pt-4"><span class="font-display text-2xl font-bold text-coral">01</span><h3 class="mt-7 text-sm font-extrabold">Choose a direction</h3><p class="mt-2 text-xs leading-5 text-slate-500">Explore clear paths built by people who know the work.</p></div><div class="border-t-2 border-ink pt-4"><span class="font-display text-2xl font-bold text-ink">02</span><h3 class="mt-7 text-sm font-extrabold">Make time for it</h3><p class="mt-2 text-xs leading-5 text-slate-500">Short, practical lessons designed for real schedules.</p></div><div class="border-t-2 border-slate-300 pt-4"><span class="font-display text-2xl font-bold text-slate-400">03</span><h3 class="mt-7 text-sm font-extrabold">Put it to work</h3><p class="mt-2 text-xs leading-5 text-slate-500">Turn new knowledge into something useful today.</p></div></div></div></section>
    </main>

    <footer id="footer" class="bg-ink text-white"><div class="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-8 sm:flex-row sm:items-center sm:px-8 lg:px-10"><div class="flex items-center gap-3"><span class="flex h-8 w-8 items-center justify-center rounded-lg bg-coral text-sm font-extrabold">A</span><span class="font-display text-base font-bold">atlas<span class="text-coral">.</span></span></div><p class="text-[11px] font-semibold text-slate-500">Learn something that moves you forward.</p><a href="{{ route('admin.login') }}" class="text-xs font-extrabold text-coral hover:underline">Admin portal →</a></div></footer>
</body>
</html>
